<?xml version="1.0"?>

<robot xmlns:xacro="http://ww.ros.org/wiki/xacro" name="diff_robot">
    
    <xacro:property name="height_offset" value="0.135" />
    <xacro:property name="wheel_radius" value="0.15" />
    <xacro:property name="wheel_thickness" value="0.1" />

    <link name="base_footprint">
    </link>

    <link name="base_link">
        <visual>
            <geometry>
                <box size="0.8 0.7 0.1" />
            </geometry>
            <material name="LightGrey">
                <color rgba="0.7 0.7 0.7 1.0"/>
            </material>
            <origin xyz="0.250 0.0 0.0" rpy="0.0 0.0 0.0"/>
        </visual>
        <collision>
            <geometry>
                <box size="0 0 0" />
            </geometry>
        </collision>
        <inertial>
            <mass value="0.0"/>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <inertia ixx="0.0" ixy="0.0" ixz="0.0" iyy="0.0" iyz="0.0" izz="0.0"/>
        </inertial>
    </link>
    
    <joint name="base_joint" type="fixed">
        <parent link="base_footprint"/>
        <child link="base_link"/>
        <origin xyz="0 0 ${height_offset}" rpy="0 0 0"/>
        <axis xyz="0 0 0"/>
    </joint>

    <xacro:macro name='wheel' params='name x_offset wheel_separation'>  
        <link name="wheel_${name}_link">
            <visual>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
                </geometry>
                <material name="Red">
                    <color rgba="1. 0. 0. 1"/>
                </material>
            </visual>
            <collision>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
                </geometry>
            </collision>
            <inertial>
                <mass value="0.0"/>
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
                <inertia ixx="0.0" ixy="0.0" ixz="0.0" iyy="0.0" iyz="0.0" izz="0.0"/>
            </inertial>
        </link>

        <joint name="wheel_${name}_joint" type="continuous">
            <parent link="base_link"/>
            <child link="wheel_${name}_link"/>
            <origin xyz="${x_offset} ${wheel_separation/2} 0" rpy="${-pi/2} 0 0"/>
            <axis xyz="0 0 1"/>
        </joint>
    </xacro:macro>

    <!-- Right wheel-->
    <xacro:wheel name="right" x_offset="0" wheel_separation="0.80"/>

    <!-- Left Wheel -->
    <xacro:wheel name="left" x_offset="0" wheel_separation="-0.80"/>

</robot>