<?xml version="1.0"?>

<robot xmlns:xacro="http://ww.ros.org/wiki/xacro" name="diff_robot">
    
    <!-- Every value is in SI units -->
    <xacro:property name="height_offset" value="0.135" />

    <xacro:property name="chassis_length" value="0.8" />
    <xacro:property name="chassis_width" value="0.7" />
    <xacro:property name="chassis_height" value="0.1" />
    <xacro:property name="chassis_mass" value="2" />

    <xacro:property name="wheel_radius" value="0.15" />
    <xacro:property name="wheel_thickness" value="0.1" />
    <xacro:property name="wheel_mass" value="0.3" />

    <xacro:property name="castor_radius" value="0.05" />
    <xacro:property name="castor_x_offset" value="0.55" />
    <xacro:property name="castor_mass" value="0.1" />


    <link name="base_footprint">
    </link>

    <link name="base_link">
        <visual>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}" />
            </geometry>
            <material name="LightGrey">
                <color rgba="0.7 0.7 0.7 1.0"/>
            </material>
            <origin xyz="0.250 0.0 0.0" rpy="0.0 0.0 0.0"/>
        </visual>
        <collision>
            <geometry>
                <box size="0 0 0" />
            </geometry>
        </collision>
        <inertial>
            <mass value="0.0"/>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <inertia ixx="${1/12*chassis_mass*(pow(chassis_height,2)+pow(chassis_length,2))}" ixy="0.0" ixz="0.0" iyy="${1/12*chassis_mass*(pow(chassis_width,2)+pow(chassis_height,2))}" iyz="0.0" izz="${1/12*chassis_mass*(pow(chassis_width,2)+pow(chassis_length,2))}"/>
        </inertial>
    </link>
    
    <joint name="base_joint" type="fixed">
        <parent link="base_footprint"/>
        <child link="base_link"/>
        <origin xyz="0 0 ${height_offset}" rpy="0 0 0"/>
        <axis xyz="0 0 0"/>
    </joint>

    <xacro:macro name='wheel' params='name x_offset wheel_separation'>  
        <link name="wheel_${name}_link">
            <visual>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
                </geometry>
                <material name="Red">
                    <color rgba="1. 0. 0. 1"/>
                </material>
            </visual>
            <collision>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
                </geometry>
            </collision>
            <inertial>
                <mass value="0.2"/>
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
                <inertia ixx="${1/12*wheel_mass*(3*pow(wheel_radius,2)+pow(wheel_thickness,2))}" ixy="0.0" ixz="0.0" iyy="${1/12*wheel_mass*(3*pow(wheel_radius,2)+pow(wheel_thickness,2))}" iyz="0.0" izz="${1/2*wheel_mass*pow(wheel_radius,2)}"/>
            </inertial>
        </link>

        <joint name="wheel_${name}_joint" type="continuous">
            <parent link="base_link"/>
            <child link="wheel_${name}_link"/>
            <origin xyz="${x_offset} ${wheel_separation/2} 0" rpy="${-pi/2} 0 0"/>
            <axis xyz="0 0 1"/>
        </joint>
    </xacro:macro>

    <link name="castor_link">
        <visual>
            <geometry>
                <sphere radius="${castor_radius}"/>
            </geometry>
            <material name="LightGrey">
                <color rgba="0.7 0.7 0.7 1.0"/>
            </material>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${castor_radius}"/>
            </geometry>
        </collision>
        <inertial>
            <mass value="0.0"/>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <inertia ixx="${2/5*castor_mass*pow(castor_radius,2)}" ixy="0.0" ixz="0.0" iyy="${2/5*castor_mass*pow(castor_radius,2)}" iyz="0.0" izz="${2/5*castor_mass*pow(castor_radius,2)}"/>
        </inertial>
    </link>

    <joint name="castor_joint" type="fixed">
        <parent link="base_link"/>
        <child link="castor_link"/>
        <origin xyz="${castor_x_offset} 0 ${-height_offset + castor_radius/2}" rpy="0 0 0"/>
        <axis xyz="0 0 0"/>
    </joint>

    <!-- Right wheel-->
    <xacro:wheel name="right" x_offset="0" wheel_separation="0.80"/>

    <!-- Left Wheel -->
    <xacro:wheel name="left" x_offset="0" wheel_separation="-0.80"/>

</robot>